### ISSUE TITLE
[Bug] Error codes during onboarding are inconsistent to former implementation

### ISSUE THREAD

**Issue by saschadoemer** [DKE-Data/agrirouter#12]
### What happened?

For full details how I discovered the bug, please see the following issue in the .NET SDK:

https://github.com/DKE-Data/agrirouter-sdk-dotnet-standard/issues/135

Running the test case using the former environment will return an error code `0401`, the current implementation on QA returns `401`. This could break current implementations.

The test using the former QA environment:

![image](https://github.com/user-attachments/assets/f6af2f9b-ea41-4bda-9d8d-b26243fd6860)

The test against the current QA environment:

![image](https://github.com/user-attachments/assets/41035f26-f8d4-42c8-88fe-aac340125c3f)

See the following PR to have more details. I will release the current version of the SDK to provide support for the test event on 2024-07-23, please keep me informed when the issue is fixed and released.

### agrirouter SDK

C#/.NET

**Comment by tim-reply** [comment]
Java SDK seem to expect there a number - https://github.com/DKE-Data/agrirouter-sdk-java/blob/296ffd05e885dea7c8ed9af285fd49af8f3b69f2/agrirouter-sdk-java-api/src/main/kotlin/com/dke/data/agrirouter/api/dto/onboard/OnboardingError.kt#L14
 (not a string) and I recall it failing to parse json if code was given it as a `"code": "0401"`. Is there a bug in Java SDK?

**Comment by saschadoemer** [comment]
@tim-reply that's right. The Java SDK will use the value as int and will remove the leading zeros. Which is fine, but the value expected would be the one from the .NET SDK.
