### ISSUE TITLE
[Question] Publishing messages on the command topic of the endpoints does not return the messages

### ISSUE THREAD

**Issue by saschadoemer** [DKE-Data/agrirouter#17]
The agrirouter-middleware is using a special mechanism to check the health status of an endpoint. A small message is published to the command topic of the endpoint.

![image](https://github.com/user-attachments/assets/f28b1be1-5418-44b0-9fe3-1e2741e792af)

This was quite charming, because the agrirouter is not flooded with "fake" messages to ensure endpoint health checking. In the current implementation, this seems to be no longer possible, causing a breaking change in the middleware.  The message on the own topic is no longer delivered to the client itself, either because it is filtered or blocked.

Which way would you recommend checking the health of an endpoint without causing unnecessary load on the agrirouter?

**Comment by oliverrahner** [comment]
This feature has just been deployed to QA.
Keep in mind, though, that this is just a hacky workaround and will hopefully be replaced by a cleaner solution in the future.
If and how long we will keep this workaround available has to be discussed then.
