### ISSUE TITLE
[Bug] Passing redirect_uri in authorize gives 500

### ISSUE THREAD

**Issue by pb-aw-nl** [DKE-Data/agrirouter#19]
### Contact Details

helpdesk@farmmaps.eu

### What happened?

**With redirect_uri fails** (500 Internal Server Error)
GET https://app.qa.agrirouter.farm/application/323263df-4e54-11ef-a95b-d2e1bbd0b244/authorize?response_type=onboard&state=10ac3e3a-c5b8-40b5-bd52-275726bf42db&redirect_uri=http://localhost:8082/en/agrirouter/cb

**Without redirect_uri succeeds** (200 OK)
https://app.qa.agrirouter.farm/en/application/323263df-4e54-11ef-a95b-d2e1bbd0b244/authorize?response_type=onboard&state=f18366da-5fc0-430c-86d1-75783ecbf314

### agrirouter SDK

No SDK

### Support Data

```json
These are settings from InOut-Tool - 2024-07-30, 09:55:29 as this endpoint isn't created yet (onboarding failed)

{
    "application_id": "a54f9c26-11fd-11ef-a875-c29f3399dfd2",
    "version_id": "05dfd25c-11fe-11ef-a875-c29f3399dfd2",
    "account_id": "bbb7040c-bcae-4e44-b6ec-de5bb6ed5f79",
    "endpoint_id": "a5d8bd07-8c96-42f9-8b52-418a9971bca4",
    "endpoint_external_id": "urn:inout:mqtt:7a048e86-42bf-4617-a191-3bda45eab999"
}
```

**Comment by oliverrahner** [comment]
Can you elaborate on what _step_ of the process actually failed?
I guess it's not calling the URLs you provided directly, but the subsequent onboarding call?

**Comment by pb-aw-nl** [comment]
It failed after pressing the CONNECT button. But the strange thing is, that it works now. I was able to onboard and the backend redirected to the right page. I am sure that this didn't work yesterday
