### ISSUE TITLE
[Known Issue] "Application Tester" feature not available yet

### ISSUE THREAD

**Issue by pb-aw-nl** [DKE-Data/agrirouter#20]
### Contact Details

helpdesk@farmmaps.eu

### What happened?

<img width="655" alt="image" src="https://github.com/user-attachments/assets/550bb406-b208-4611-b168-67f4502231e5">
<img width="529" alt="image" src="https://github.com/user-attachments/assets/28495fc6-1bc8-477f-93e3-af9a0f0e1dd3">
<img width="360" alt="image" src="https://github.com/user-attachments/assets/2e465762-fe21-4f11-bee4-7f4f8552bbbf">

### agrirouter SDK

No SDK

### Support Data

```json
{
    "application_id": "323263df-4e54-11ef-a95b-d2e1bbd0b244",
    "version_id": "d2236c51-4e54-11ef-a95b-d2e1bbd0b244",
    "account_id": "bbb7040c-bcae-4e44-b6ec-de5bb6ed5f79",
    "endpoint_id": "6450bb0b-175c-4dc6-862d-64e3320f826d",
    "endpoint_external_id": "urn:uuid:9ae7d5ef-9b84-468d-b6c5-0024ffb1ab54"
}
```

### Additional information

- https://app.qa.agrirouter.farm/en/settings/testers
- settings
- testers
- Add a tester

**Comment by AlexisZankowitch** [comment]
Hi,

The application tester is currently not deployed to QA therefore you won't be able to try this feature for now. I am sorry for the inconvenience. We hope to make this feature available in the upcoming weeks.

**Comment by AlexisZankowitch** [comment]
It is now possible for Tenant to test your own applications version which have the `APPROVED_FOR_TESTING` status

**Comment by oliverrahner** [comment]
We are currently working on completing this feature, but it will still be some weeks till ETA.

**Comment by oliverrahner** [comment]
The testers feature has gone live yesterday night, and is now fully available!
