### ISSUE TITLE
connection not allowed for a router device that tries to connect to a revoked endpoint 

### ISSUE THREAD

**Issue by AlexisZankowitch** [DKE-Data/agrirouter#21]
### What happened?

During the testing summit taking place in Osnabrück we faced an issue with the **agrirouter middleware** because a router-device was trying to establish a connection for several endpoints including one that was previously revoked. 

The gateway validates if the router-device can connect or not to specific topics based on:
- endpoint being valid (not deleted)
- the software of the endpoint belongs to the same tenant than the router device 

### agrirouter SDK

No SDK

**Comment by oliverrahner** [comment]
This has been "fixed" such that:

* we now allow publish/subscribe to endpoints' topics for a grace period (currently 7 days) after deletion of an endpoint; technically we are only soft-deleting the endpoint for that grace period, but we eventually need to clean up
* we added a new command `dke:ping` to agrirouter, to provide a reliable way to determine if an endpoint is still valid or not

However, after that grace period, we will again kill router device connections of devices that try to publish to a topic of an endpoint that doesn't exist.
