### ISSUE TITLE
[Bug] reponse ACK_FOR_FEED_HEADER_LIST has SensorAlternateId 00000000-0000-0000-0000-000000000000

### ISSUE THREAD

**Issue by oliverrahner** [DKE-Data/agrirouter#25]
### Contact Details

l.timphaus@grimme.de

### What happened?

When receiving an ACK_FOR_FEED_HEADER_LIST, the SensorAlternateId is 00000000-0000-0000-0000-000000000000.

![image](https://github.com/user-attachments/assets/aa6f775e-d733-434d-a658-d21022ce3765)

EDIT: We received additional information: 

This seems to also be true for ACK_FOR_FEED_MESSAGE. We should check if this is general problem for all responses.

### agrirouter SDK

C#/.NET

### Support Data

```json
{
    "application_id": "4375caee-49bd-11ef-a95b-d2e1bbd0b244",
    "version_id": "eb9eced4-4f41-11ef-a95b-d2e1bbd0b244",
    "account_id": "55191188-a25c-4252-bac0-22ba26a72b79",
    "endpoint_id": "0c139205-c101-4ce6-b761-d57de7ca7eb6",
    "endpoint_external_id": "urn:extid:68309905"
}
```

### Additional information

The related feed header query payload:
`SwokYmJkODc4ZTAtOGM5Zi00Yjc4LWEwMTAtOWY1N2Y3NTBhYjkwEAQaFWRrZTpmZWVkX2hlYWRlcl9xdWVyeUIKCPr+97UGEMCEPUYKRAokYWdyaXJvdXRlci5mZWVkLnJlcXVlc3QuTWVzc2FnZVF1ZXJ5EhwaGgoLCLSgw7UGEPTfiBoSCwi0/ve1BhCUvJ9J`

**Comment by AlexisZankowitch** [comment]
If it's !vcu sensorAlternateId is the endpointId, if it's a vCU it should be the identifier of the vCU

**Comment by AlexisZankowitch** [comment]
We need to make sure that it's not a general issue. And the sensorAlternateId is correctly set for all commands

**Comment by oliverrahner** [comment]
The fix has been implemented and pushed to QA.
Will be closed after confirmation from testers.

**Comment by oliverrahner** [comment]
We got confirmation by testers that this issue is indeed gone!
