### ISSUE TITLE
[Bug] When sending File from VCU to endpoint without routing, the MessageSentFailure is sent to Telemetry Platform

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter#28]
### Contact Details

info@dev4Agriculture.de

### What happened?

Scenario: Telemetry Platform; 1 Platform instance onboarded, this Platform instance has one VCU onboarded
The following works as expected: Set a routing from the VCU to any other endpoint (e.g. IO-Tool) and send a file. The ACK will be returned marking the VCU as receiver

The following does *not* work: Remove the routing and send a file. The Error is returned towards the Telemetry Platform, not towards the VCU

### agrirouter SDK

C#/.NET

**Comment by AlexisZankowitch** [comment]
Hi Frank, 

Thank you for reporting the issue. May I know if it's an issue you faced in a real life scenario or if it's something you stubble upon while testing the platform?

**Comment by Frank-Wiebeler** [comment]
It's a real life scenario I faced while testing the Platform :)

Imagine you want to send a file from a VirtualCU. You request the endpoints to send to. While you're doing this (Maybe even directly on the virtual cu, so really somewhere in the fields), another user removes the routing between your VCU and the target software.

You click on "Send", try to send and would receive back the error. But as it goes to the platform itself, there's an unrelated error shown in the platform while you on your machine think everything went fine.

**Comment by AlexisZankowitch** [comment]
Hi @Frank-Wiebeler ,

We published a fix for this issue. From our perspective this can be marked as solved. Could you confirm from your side?

**Comment by oliverrahner** [comment]
This will now be closed until further notice.
@Frank-Wiebeler if you recognize this might still be an issue, please feel free to let us know.
