### ISSUE TITLE
[Known Issue] User doesn't have a tenant

### ISSUE THREAD

**Issue by AlexisZankowitch** [DKE-Data/agrirouter#3]
_Old issue name: tenant creation failed - after registration_ 

It might happen that your tenant didn't get created after your registration. If it is the case you will see a dialog popping up on your screen when you visit the Farmer page. 

If after registration you get a keycloak error you will most certainly face this issue. Please, use this discussion to let me know and I can create a tenant for you and assign it to your user.

We are currently working on the registration flow so we expect to fix this issue when we will be ready to deliver it to QA.

**Comment by capke** [comment]
Hi Alexis, 
can you please create a tenant for the user: c.apke@dke-data.com?

**Comment by AlexisZankowitch** [comment]
> Hi Alexis, can you please create a tenant for the user: [c.apke@dke-data.com](mailto:c.apke@dke-data.com)?

I associated a tenant with your user @capke.

**Comment by oliverrahner** [comment]
At least two instances of this have been seen today. We still need to fix this.

**Comment by AlexisZankowitch** [comment]
We have identified what could be the main reason of the issue and we will be able to deploy a fix soon

**Comment by AlexisZankowitch** [comment]
The fix has been deployed
