### ISSUE TITLE
[Migration Issue] Tester migration was incomplete 

### ISSUE THREAD

**Issue by oliverrahner** [DKE-Data/agrirouter#32]
### What happened?

During migration, for certain developer accounts the "testers" (https://app.agrirouter.com/en/settings/testers) were not correctly migrated.
We will fix the migration scripts and rerun for these cases.

### agrirouter SDK

No SDK

**Comment by AlexisZankowitch** [comment]
Could you provide me the application tenant and one of the user that could test this application?

**Comment by oliverrahner** [comment]
In connection with #20, we repeated the testers migration again today. All testers that might have been added in the meantime were kept in place, but we also added the ones that were present in the old system.
