### ISSUE TITLE
[Bug] Save preferred softwares do not appear in the Office column of my agrirouter

### ISSUE THREAD

**Issue by AlexisZankowitch** [DKE-Data/agrirouter#35]
### What happened?

After saving a software we would expect it to appear in a empty box of the office column. 

### agrirouter SDK

No SDK

**Comment by tim-reply** [comment]
This should be fixed on prod now, at least in my account where it was reproducing, I can see the boxes now  again

![image](https://github.com/user-attachments/assets/d8057b55-0807-453c-a5de-efd2d558d38d)
