### ISSUE TITLE
[Bug] Some devices still using (very) old onboarding hostnames can't be (re)onboarded 

### ISSUE THREAD

**Issue by oliverrahner** [DKE-Data/agrirouter#37]
### What happened?

We recognized that some devices and applications in the field are still using hostnames `agrirouter-registration-service.cfapps.eu10.hana.ondemand.com` (deprecated in 2020) or `agrirouter-registration-service.cfapps.eu1.hana.ondemand.com` (deprecated in 2019).
As these hostnames still point to the old, to be decommissioned, infrastructure, during onboarding this error is to be expected:
```
{
    "error": {
        "code": "0401",
        "message": "Bearer not found.",
        "target": "",
        "details": []
    }
}
```

A solution for `agrirouter-registration-service.cfapps.eu10.hana.ondemand.com` is already in place, proxying requests to that hostname to the new and correct `onboard.agrirouter.com`.

A solution for `agrirouter-registration-service.cfapps.eu1.hana.ondemand.com` will hopefully be put into place soon.

### agrirouter SDK

No SDK

**Comment by ThomasLechner-xarvio** [comment]
I tried to fix it by changing the URL on the device. (I still had eu1)

With this one it worked:
https://agrirouter-registration-service.cfapps.eu10.hana.ondemand.com/api/v1.0/registration/onboard

These did not work:
https://onboard.agrirouter.com/api/v1.0/registration/onboard
https://onboard.agrirouter.com/

**Comment by oliverrahner** [comment]
@ThomasLechner-xarvio: 
This one *should really* work: https://onboard.agrirouter.com/api/v1.0/registration/onboard (the other one, without the path, can't).
If you can't make it work, we should look at it together (probably best to contact @capke for this), because then we need to find out why!
Using the `eu10` hostname still relies on our proxying workaround, and it _will_ be somehow temporary, whatever that means :) Most probably years.

**Comment by oliverrahner** [comment]
A fix for the `eu1` host name has put in place today!
