### ISSUE TITLE
[Bug] Incoming PushNotification has same MessageId as Outgoing FileSending MessageId from other Endpoint

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter#38]
### Contact Details

frank.wiebeler@dev4Agriculture.de

### What happened?

Scenario: 1 Application with 2 Instances connected to the same agrirouter account. We want to send files from 1 Instance to the other one
What to do: Send a file from UserA to UserB in the FarmingSoftware (both connected in the same agrirouter account)

What you would like to do: 
- As UserA, you want to confirm that your message was sent, so you're waiting for an ACK. You are able to assign the ACK to the correct message by its messageId
- As UserB, you want to receive a PushNotification. Initially you won't care about the messageId as you don't know it anyway.

What's the problem:
- The PushNotification has the same MessageId as the sent File Message

Why is this a problem:
- Most applications try to assign incoming messages to the messageId. If they filter for ID first and only afterwards for type of message, you might miss the PushNotification or will never get an Acknowledgement for sending a file.

WorkAround:
- You can of course filter for messageId AND ReceiverId. Problematic is that we don't know how it's implemented out there.

### agrirouter SDK

No SDK

**Comment by oliverrahner** [comment]
Hi @Frank-Wiebeler,

as discussed previously, this was a conscious design choice.
Previously, there was no end-to-end relationship between messages sent by one endpoint and the messages received by other endpoints. This is not done utilizing the Message Id.
Give the slim chance of this going actually wrong in a production scenario _and_ the fact that there are several ways to correctly handle this (look at the recipient, look at the Response Type, look at the topic you got the message from...), we decided to keep the behavior that way.
We might add a specific remark for this to the documentation, though.
