### ISSUE TITLE
[Bug] Files sent to VirtualCU are provided as PushNotification for the Telemetry Platform

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter#39]
### Contact Details

frank.wiebeler@dev4Agriculture.de

### What happened?

What was done:
- We onboarded 2 instances of a Telemetry Platform A and B. 
- Each of these platforms onboard one VirtualCU (A1 and B1)
- We tried to send a file from A to B1 and B to A1

What went wrong:
- When sending to B1, we receive a pushNotification with the file for ReceiverID B (not B1). 
- We can send a confirmation for this message without any error
- When requesting the FeedMessages for B1, we receive the file for ReceiveId B1

Workaround:
- None, it's screwed :) 

### agrirouter SDK

C#/.NET

**Comment by AlexisZankowitch** [comment]
Hi Frank,

Thank you for reporting the issue. The team is having a look 👍

**Comment by oliverrahner** [comment]
There is another detail with a very similar bug:
When receiving data *sent by a VCU* via Push Notification, the sender in the message was the *telemetry platform* of that VCU.

**Comment by oliverrahner** [comment]
Both bugs have been fixed an deployed ~20 minutes ago.
