### ISSUE TITLE
[Bug] Command `feed_header_query` will confirm and remove the first message of the feed

### ISSUE THREAD

**Issue by kuhnbv** [DKE-Data/agrirouter#44]
### Contact Details

dev_agrirouter@kuhn.com

### What happened?

When requesting the message ids from an endpoint feed, the first message of the response list will be confirmed without sending any `feed_confirm` command.

This can lead to missing message/chunk if we request the feed but don't query directly the messages afterwards.

### agrirouter SDK

C#/.NET

**Comment by oliverrahner** [comment]
We are currently investigating this.
The logic for confirmation/message deletion is pretty much completely separate from the querying part, so it’s not clear to us yet where or why this might occur, but we will keep you posted.

**Comment by kuhnbv** [comment]
> We are currently investigating this. The logic for confirmation/message deletion is pretty much completely separate from the querying part, so it’s not clear to us yet where or why this might occur, but we will keep you posted.

We've done more testing on our side and we spotted an issue in our configuration : our local environment was listening to the same endpoints as our staging environment. So each MQTT command was processed two time by two differents environments, causing some conflicts.

**Comment by oliverrahner** [comment]
Oh, good to hear!
So you agree that the original issue does not exist on our side?

**Comment by kuhnbv** [comment]
Yes It was a misconfiguration in our environments.
