### ISSUE TITLE
[Bug] Login & Back to the application - Bad Request

### ISSUE THREAD

**Issue by Pfauwadel** [DKE-Data/agrirouter#6]
### Contact Details

damien.pfauwadel@kuhn.com

### What happened?

I've filled the form and access to the authentication process. The link "back to the application" generate a 400 bad request. 
![2024-07-01_10h04_45](https://github.com/DKE-Data/agrirouter/assets/31513598/45225ef6-f2c3-47bf-92ab-52c81d2ceb83)

### agrirouter SDK

No SDK

**Comment by AlexisZankowitch** [comment]
Hi Damien,

Have you tried to create your user one more time. We have some issues with our registration process that are known (see #3 ). Your issue might be related. 

If when trying one more time could you copy the request and response object here as well? 

I can see a user created with the following email address: dev_agrirouter@kuhn.com that has your name and lastname. Do you required another user as well?

**Comment by AlexisZankowitch** [comment]
Hi Damien, 

I will close this issue as we will anyway rework the registration process, and your specific issue was fixed.
