### ISSUE TITLE
[Known Issue] CCI terminals with software version 3 cannot establish a agrirouter connection after restarting

### ISSUE THREAD

**Issue by capke** [DKE-Data/agrirouter#9]
### Contact Details

c.apke@dke-data.com

### What happened?

If a CCI terminal is trying to update its unchanged capabilities, e.g. after a restart, the backend responds with the message: 
_"Skipping capabilities update because there are no differences." "Skipping capabilities update because there are no differences."_

The terminal interrupts the further connection to the agrirouter backend.

This problem does not occur with terminals with software version 4, the terminal software ignores this warning.

### agrirouter SDK

No SDK

### Support Data

```json
{
    "application_id": "053910eb-2720-11ef-83e6-7e16a487ea59",
    "version_id": "073be6c6-2720-11ef-83e6-7e16a487ea59",
    "account_id": "4a9ee5bd-fd45-4305-a6cc-2a0e9ac864d1",
    "endpoint_id": "6a2a3472-5c05-40ee-8e82-a5ebbb20a660",
    "endpoint_external_id": "CCI1200-0602283_e9130895-bdbc-48cb-a865-aa56389de03b"
}
```

**Comment by AlexisZankowitch** [comment]
It should be solved with the current release 18/07
